### ISSUE TITLE
Unhandled exception with customized TKAPE file

### ISSUE THREAD

**Issue by sjosz** [EricZimmerman/KapeFiles#217]
** KAPE version # **
0.9.2.0

**Describe the bug**
When running KAPE with a customized tkape file using regex:

**To Reproduce**

1) Create a custom tkape file

`Description: Potential malware
Author: J
Version: 1.0
Id: c94f9a6e-51f0-45af-9f46-f29651736446
RecreateDirectories: True
Targets:
    -
        Name: Potential malware samples
        Category: Custom
        Path: C:\ProgramData\
        FileMask: regex:.+.(exe|bat)`

2) I'm running kape with the following parameters: 

--tsource C:\ --tdest .\Collected\%m\KAPE_Triage --target WindowsTimeline,KapeTriage,Antivirus,Custom --zip %m --cu --zpw "password" --zm --VSS --ifw --gui

**Screenshots**
`
Parameter name: path:    at Alphaleonis.Win32.Filesystem.Path.CheckInvalidPathChars(String path, Boolean checkAdditional, Boolean allowEmpty) in C:\Users\jjangli\Documents\GitHub\AlphaFS\AlphaFS\Filesystem\Path Class\Path.Helpers.cs:line 115
   at Alphaleonis.Win32.Filesystem.Path.IsPathRooted(String path, Boolean checkInvalidPathChars) in C:\Users\jjangli\Documents\GitHub\AlphaFS\AlphaFS\Filesystem\Path Class\Path.IsPathRooted.cs:line 73
   at Alphaleonis.Win32.Filesystem.Path.CombineCore(Boolean checkInvalidPathChars, String[] paths) in C:\Users\jjangli\Documents\GitHub\AlphaFS\AlphaFS\Filesystem\Path Class\Path.Combine.cs:line 67
   at kape.Classes.Helpers.GetFilesFromPath(String path, Boolean recursive, String fileMask, Boolean alwaysAdd, Nullable`1 minSize, Nullable`1 maxSize)
   at kape.Program.ExpandTarget(Target target)
   at kape.Program.ProcessTarget(Target target, String startDirectory)
   at kape.Program.LoadTargetFile(TargetCollection targetFile)
   at kape.Program.LoadTargetFile(TargetCollection targetFile)
   at kape.Program.Main(String[] args)
2020-06-23 09:58:59.8778 | W | Unhandled exception! Attempting to write current Console Log to 'C:\Users\User\Desktop\KAPE_collector - Copy\2020-06-23T07_58_51_8460082_ConsoleLog.txt'
`

I'm not sure what I'm doing wrong here. I checked the documentation and tried different regexes. When not using the regex everything works - but it is a great feature and I would like to use it to collect polymorphic malware.

**Comment by EricZimmerman** [comment]
why do you have ifw set? did you mount an image with FTK imager?

why are you using --cu? that is related to batch mode

why are you using --zm, that has to do with module output which there are none here

please email me the tkape file along with ConsoleLog when running with --debug and --trace

**Comment by sjosz** [comment]
With regards to the parameters - yes indeed I'm running it in batch mode and no we never use FTK combined with KAPE. The --zm should indeed not be there, I removed it now.

Here you have the debug and tkape file: [Debug.zip](https://github.com/EricZimmerman/KapeFiles/files/4819423/Debug.zip)

**Comment by EricZimmerman** [comment]
is there a reason you did not include

        Recursive: true

in the target file?

it seems related to this. ill run it thru and fix this case, but i wanted to make sure you saw this and understand that only the Path folder will be searched without the above line

**Comment by sjosz** [comment]
Thank you!

Yes, that is on purpose. I want KAPE to collect malware from a few common locations such as for example the root of ProgramData or the root of a user profile folder.

**Comment by EricZimmerman** [comment]
k that helps. looking now

**Comment by EricZimmerman** [comment]
ok this is fixed.

stupid error on my part. had to move a path check inside an if statement. that was it!


please check for update and let me know
0903 is now available that fixes this

**Comment by sjosz** [comment]
Shit happens. Thanks for fixing it so fast Eric!
