### ISSUE TITLE
"Error copying file: Out of disk space"

### ISSUE THREAD

**Issue by BeanBagKing** [EricZimmerman/KapeFiles#28]
We are attempting to run KAPE against a hard drive connected via write blocker. The command line used is as follows: `kape.exe --tsource D --target !ALL --vss true --vhdx test123 -tdest "c:\Users\itss\Desktop\test123" --trace --debug`

This should be using the latest targets (from this GitHub), but the behavior appears to be the same. The physical disk (C:\) that the VHDX is being written to has plenty of space. We've run this multiple times with various options (--vss false, --vhd test123). Not creating a vhd/x does seem to work (it has no problems copying the $MFT file). However, when adding it to the virtual disk, we get the following errors.

```
Adding 'c:\Users\itss\Desktop\test123\D\\$MFT' to VHDX
Destination filename '\D\\$MFT' / Destination '\D\'
Copying '\D\\$MFT' to VHDX
System.IO.IOException: Out of disk space
   at DiscUtils.Ntfs.ClusterBitmap.AllocateClusters(Int64 count, Int64 proposedStart, Boolean isMft, Int64 total)
   at DiscUtils.Ntfs.RawClusterStream.AllocateClusters(Int64 startVcn, Int32 count)
   at DiscUtils.Ntfs.RawClusterStream.ExpandToClusters(Int64 numVirtualClusters, NonResidentAttributeRecord extent, Boolean allocate)
   at DiscUtils.Ntfs.NonResidentAttributeBuffer.SetCapacity(Int64 value)
   at DiscUtils.Ntfs.NonResidentAttributeBuffer.Write(Int64 pos, Byte[] buffer, Int32 offset, Int32 count)
   at DiscUtils.Ntfs.NtfsAttributeBuffer.Write(Int64 pos, Byte[] buffer, Int32 offset, Int32 count)
   at DiscUtils.Streams.BufferStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at DiscUtils.Ntfs.NtfsFileStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Stream.InternalCopyTo(Stream destination, Int32 bufferSize)
   at kape.Program.CreateVhdx(Boolean asVhd)
Error copying file 'c:\Users\itss\Desktop\test123\D\\$MFT' to 'c:\Users\itss\Desktop\test123\2019-03-04T202614_!ALL_test123.vhdx': Out of disk space
Adding 'c:\Users\itss\Desktop\test123\D\\$LogFile' to VHDX
Destination filename '\D\\$LogFile' / Destination '\D\'
Copying '\D\\$LogFile' to VHDX
System.IO.IOException: Out of disk space
   at DiscUtils.Ntfs.ClusterBitmap.AllocateClusters(Int64 count, Int64 proposedStart, Boolean isMft, Int64 total)
   at DiscUtils.Ntfs.RawClusterStream.AllocateClusters(Int64 startVcn, Int32 count)
   at DiscUtils.Ntfs.RawClusterStream.ExpandToClusters(Int64 numVirtualClusters, NonResidentAttributeRecord extent, Boolean allocate)
   at DiscUtils.Ntfs.NonResidentAttributeBuffer.SetCapacity(Int64 value)
   at DiscUtils.Ntfs.NonResidentAttributeBuffer.Write(Int64 pos, Byte[] buffer, Int32 offset, Int32 count)
   at DiscUtils.Ntfs.NtfsAttributeBuffer.Write(Int64 pos, Byte[] buffer, Int32 offset, Int32 count)
   at DiscUtils.Streams.BufferStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at DiscUtils.Ntfs.NtfsFileStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Stream.InternalCopyTo(Stream destination, Int32 bufferSize)
   at kape.Program.CreateVhdx(Boolean asVhd)
Error copying file 'c:\Users\itss\Desktop\test123\D\\$LogFile' to 'c:\Users\itss\Desktop\test123\2019-03-04T202614_!ALL_test123.vhdx': Out of disk space
Adding 'c:\Users\itss\Desktop\test123\D\\$Extend\$J' to VHDX
Destination filename '\D\\$Extend\$J' / Destination '\D\\$Extend'
Creating destination directory '\D\\$Extend'
Copying '\D\\$Extend\$J' to VHDX
System.IO.IOException: Out of disk space
   at DiscUtils.Ntfs.ClusterBitmap.AllocateClusters(Int64 count, Int64 proposedStart, Boolean isMft, Int64 total)
   at DiscUtils.Ntfs.RawClusterStream.AllocateClusters(Int64 startVcn, Int32 count)
   at DiscUtils.Ntfs.RawClusterStream.ExpandToClusters(Int64 numVirtualClusters, NonResidentAttributeRecord extent, Boolean allocate)
   at DiscUtils.Ntfs.NonResidentAttributeBuffer.SetCapacity(Int64 value)
   at DiscUtils.Ntfs.NonResidentAttributeBuffer.Write(Int64 pos, Byte[] buffer, Int32 offset, Int32 count)
   at DiscUtils.Ntfs.NtfsAttributeBuffer.Write(Int64 pos, Byte[] buffer, Int32 offset, Int32 count)
   at DiscUtils.Streams.BufferStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at DiscUtils.Ntfs.NtfsFileStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Stream.InternalCopyTo(Stream destination, Int32 bufferSize)
   at kape.Program.CreateVhdx(Boolean asVhd)
Error copying file 'c:\Users\itss\Desktop\test123\D\\$Extend\$J' to 'c:\Users\itss\Desktop\test123\2019-03-04T202614_!ALL_test123.vhdx': Out of disk space
Adding 'c:\Users\itss\Desktop\test123\D\\$Extend\$Max' to VHDX
Destination filename '\D\\$Extend\$Max' / Destination '\D\\$Extend'
Copying '\D\\$Extend\$Max' to VHDX
Adding 'c:\Users\itss\Desktop\test123\D\$Secure_$SDS' to VHDX
Destination filename '\D\$Secure_$SDS' / Destination '\D'
Copying '\D\$Secure_$SDS' to VHDX
System.IO.IOException: Out of disk space
   at DiscUtils.Ntfs.ClusterBitmap.AllocateClusters(Int64 count, Int64 proposedStart, Boolean isMft, Int64 total)
   at DiscUtils.Ntfs.RawClusterStream.AllocateClusters(Int64 startVcn, Int32 count)
   at DiscUtils.Ntfs.RawClusterStream.ExpandToClusters(Int64 numVirtualClusters, NonResidentAttributeRecord extent, Boolean allocate)
   at DiscUtils.Ntfs.NonResidentAttributeBuffer.SetCapacity(Int64 value)
   at DiscUtils.Ntfs.NonResidentAttributeBuffer.Write(Int64 pos, Byte[] buffer, Int32 offset, Int32 count)
   at DiscUtils.Ntfs.NtfsAttributeBuffer.Write(Int64 pos, Byte[] buffer, Int32 offset, Int32 count)
   at DiscUtils.Streams.BufferStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at DiscUtils.Ntfs.NtfsFileStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Stream.InternalCopyTo(Stream destination, Int32 bufferSize)
   at kape.Program.CreateVhdx(Boolean asVhd)
Error copying file 'c:\Users\itss\Desktop\test123\D\$Secure_$SDS' to 'c:\Users\itss\Desktop\test123\2019-03-04T202614_!ALL_test123.vhdx': Out of disk space
Adding 'c:\Users\itss\Desktop\test123\D\\$Boot' to VHDX
Destination filename '\D\\$Boot' / Destination '\D\'
Copying '\D\\$Boot' to VHDX
Adding 'c:\Users\itss\Desktop\test123\D\\$Extend\$RmMetadata\$TxfLog\$T' to VHDX
Destination filename '\D\\$Extend\$RmMetadata\$TxfLog\$T' / Destination '\D\\$Extend\$RmMetadata\$TxfLog'
Creating destination directory '\D\\$Extend\$RmMetadata\$TxfLog'
Copying '\D\\$Extend\$RmMetadata\$TxfLog\$T' to VHDX
System.IO.IOException: Out of disk space
   at DiscUtils.Ntfs.ClusterBitmap.AllocateClusters(Int64 count, Int64 proposedStart, Boolean isMft, Int64 total)
   at DiscUtils.Ntfs.RawClusterStream.AllocateClusters(Int64 startVcn, Int32 count)
   at DiscUtils.Ntfs.RawClusterStream.ExpandToClusters(Int64 numVirtualClusters, NonResidentAttributeRecord extent, Boolean allocate)
   at DiscUtils.Ntfs.NonResidentAttributeBuffer.SetCapacity(Int64 value)
   at DiscUtils.Ntfs.NonResidentAttributeBuffer.Write(Int64 pos, Byte[] buffer, Int32 offset, Int32 count)
   at DiscUtils.Ntfs.NtfsAttributeBuffer.Write(Int64 pos, Byte[] buffer, Int32 offset, Int32 count)
   at DiscUtils.Streams.BufferStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at DiscUtils.Ntfs.NtfsFileStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Stream.InternalCopyTo(Stream destination, Int32 bufferSize)
   at kape.Program.CreateVhdx(Boolean asVhd)
Error copying file 'c:\Users\itss\Desktop\test123\D\\$Extend\$RmMetadata\$TxfLog\$T' to 'c:\Users\itss\Desktop\test123\2019-03-04T202614_!ALL_test123.vhdx': Out of disk space
Adding 'c:\Users\itss\Desktop\test123\D\Windows\system32\Tasks\Microsoft\Windows\GroupPolicy\{3E0A038B-D834-4930-9981-E89C9BFF83AA}' to VHDX
Destination filename '\D\Windows\system32\Tasks\Microsoft\Windows\GroupPolicy\{3E0A038B-D834-4930-9981-E89C9BFF83AA}' / Destination '\D\Windows\system32\Tasks\Microsoft\Windows\GroupPolicy'
Creating destination directory '\D\Windows\system32\Tasks\Microsoft\Windows\GroupPolicy'
Copying '\D\Windows\system32\Tasks\Microsoft\Windows\GroupPolicy\{3E0A038B-D834-4930-9981-E89C9BFF83AA}' to VHDX
Adding 'c:\Users\itss\Desktop\test123\D\Windows\system32\Tasks\Microsoft\Windows\GroupPolicy\{A7719E0F-10DB-4640-AD8C-490CC6AD5202}' to VHDX
Destination filename '\D\Windows\system32\Tasks\Microsoft\Windows\GroupPolicy\{A7719E0F-10DB-4640-AD8C-490CC6AD5202}' / Destination '\D\Windows\system32\Tasks\Microsoft\Windows\GroupPolicy'
Copying '\D\Windows\system32\Tasks\Microsoft\Windows\GroupPolicy\{A7719E0F-10DB-4640-AD8C-490CC6AD5202}' to VHDX
Adding 'c:\Users\itss\Desktop\test123\D\System Volume Information\IndexerVolumeGuid' to VHDX
Destination filename '\D\System Volume Information\IndexerVolumeGuid' / Destination '\D\System Volume Information'
Copying '\D\System Volume Information\IndexerVolumeGuid' to VHDX
Adding 'c:\Users\itss\Desktop\test123\D\System Volume Information\WPSettings.dat' to VHDX
Destination filename '\D\System Volume Information\WPSettings.dat' / Destination '\D\System Volume Information'
Copying '\D\System Volume Information\WPSettings.dat' to VHDX
Copying '\2019-03-04T20_21_20_9368065_!ALL_copylog.csv' to VHDX

Unhandled Exception: System.IO.IOException: Out of disk space
   at DiscUtils.Ntfs.ClusterBitmap.AllocateClusters(Int64 count, Int64 proposedStart, Boolean isMft, Int64 total)
   at DiscUtils.Ntfs.RawClusterStream.AllocateClusters(Int64 startVcn, Int32 count)
   at DiscUtils.Ntfs.RawClusterStream.ExpandToClusters(Int64 numVirtualClusters, NonResidentAttributeRecord extent, Boolean allocate)
   at DiscUtils.Ntfs.NonResidentAttributeBuffer.SetCapacity(Int64 value)
   at DiscUtils.Ntfs.NonResidentAttributeBuffer.Write(Int64 pos, Byte[] buffer, Int32 offset, Int32 count)
   at DiscUtils.Ntfs.NtfsAttributeBuffer.Write(Int64 pos, Byte[] buffer, Int32 offset, Int32 count)
   at DiscUtils.Streams.BufferStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at DiscUtils.Ntfs.NtfsFileStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Stream.InternalCopyTo(Stream destination, Int32 bufferSize)
   at kape.Program.CreateVhdx(Boolean asVhd)
   at kape.Program.Main(String[] args)

C:\Users\itss\Desktop\KAPE>
```

**Comment by EricZimmerman** [comment]
what version of KAPE?

the error is saying that the VHDX container has run out of room, not the tdest drive,

can you run this with --debug and --trace and email me the results?

also, run the same command WITHOUT the --vhdx option, then select the tdest directory, right click and choose properties, and tell me the total number of files and the total size taken?

it may be i just need to way overallocate the size of the vhdx file and let compression deal with empty space.

thanks

**Comment by EricZimmerman** [comment]
i would also suggest against using !All or at least move the AppData target into !Disabled because its massive overkill from a collection perspective.

**Comment by BeanBagKing** [comment]
Latest available for download, 0.8.1.0 per changelog. I'll re-run and email the results first thing in the morning.

**Comment by EricZimmerman** [comment]
any update on this?

**Comment by BeanBagKing** [comment]
I'm sorry I couldn't get back to you as quickly as I hoped. Our forensics station has been tied up for the last few days. I just sent you an email containing the logs though. Please let me know if there's anything else that would help. 

AppData target does already appear to be in the !Disabled folder. I'm still running with !ALL, at least for the purposes of reproducing the issue here.

**Comment by EricZimmerman** [comment]
No problem on using all.  I'll look at logs.

Eric Zimmerman

Opinions stated, unless explicitly stated otherwise, are mine and not that
of my employer.

P // 501-313-3778

**Comment by EricZimmerman** [comment]
This appears to be resolved in the latest beta. OP to confirm and close if this is the case.

**Comment by BeanBagKing** [comment]
Confirming this is resolved. Thanks!
