### ISSUE TITLE
Kape zip issue?

### ISSUE THREAD

**Issue by darkone337** [EricZimmerman/KapeFiles#331]
When attempting to use KAPE's zip functionality I receive the following error:
```2020-12-14 21:30:30.0507 | I | Copied 1,173 (Deduplicated: 957) out of 2,130 files in 262.9814 seconds. See '*_CopyLog.csv' in the VHD(X)/Zip located in 'C:\Temp\<REDACTED>' for copy details
2020-12-14 21:30:30.0663 | W | Compressing files to 'C:\Temp\<REDACTED>’...
2020-12-14 21:31:23.4797 | F | A device attached to the system is not functioning.
:    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.Console.set_Title(String value)
   at Rebex.IO.Compression.ZipArchive.gadp(ZipProgressChangedEventArgs jo)
   at ogva.xvwj(vnxz aox)
   at vnxy.xvuu(vnxw gz)
   at vnxy.xvur()
   at vnxy.xvul(TransferAction gi, vnxu gj, String gk, TransferMethod gl, MoveMode gm, LinkProcessingMode gn, ActionOnExistingFiles go, vnxv gp)
   at ogva.yixb(ArchiveOperation xh, vnxu xi, String xj, TransferMethod xk, ActionOnExistingFiles xl)
   at Rebex.IO.Compression.ZipArchive.gagp(vnxu ra, String rb, TransferMethod rc, ActionOnExistingFiles rd)
   at kape.Program.BuildZip(String zipFileName, String comment, String password, String sourceDir)
   at kape.Program.CreateZip()
   at kape.Program.Main(String[] args)
2020-12-14 21:31:23.4797 | W | Unhandled exception! Attempting to write current Console Log to 'C:\2020-12-15T03_26_06_1132399_ConsoleLog.txt'```

Is this an error with kape or with the target host?

**Comment by EricZimmerman** [comment]
Looks like the target host to me. If you try it on your main machine does it work as expected?

**Comment by darkone337** [comment]
On some hosts it works fine, while on others it doesn't. I am also using -vss in the command line (along with aws flags). Is there a way for kape to elaborate more on which device is not functioning? My target source is C with the default SANS tkape file. 0.9.3 version

**Comment by EricZimmerman** [comment]
Maybe debug or Trace would show. 

Why aren't you using 0.9.5.0? That's the first thing I would do is update to latest

**Comment by EricZimmerman** [comment]
did 0.9.5.0 fix this? will close for now pending for info from OP

**Comment by EricZimmerman** [comment]
so in looking at this more, i saw another error like this:

System.IO.IOException: A device attached to the system is not functioning.
at System.IO.__Error.WinIOError(System.Int32 errorCode, System.String maybeFullPath) at offset 15
at System.Console.set_Title(System.String value) at offset 72
at kape.Program.Main(System.String[] args) at offset 22883


Notice the last thing that is happening before things explode:

at System.Console.set_Title(System.String value) at offset 72

Setting the title of the Console window. i dont know if this is fixable on the machine

in0.9.6.0, i wrapped setting the Title in a try/catch to prevent this
