### ISSUE TITLE
Zip option errors

### ISSUE THREAD

**Issue by Gizmo44z** [EricZimmerman/KapeFiles#44]
I'm just trying the "!ALL" target option (no modules) with a zip export format, but it is running into "Unhandled Exception: System.IO.PathTooLongException" errors and cancels the zip process. 

It looks like collecting Microsoft Edge data grabs data from here:

C\Users\[xxxUSERxxx]\AppData\Local\Packages\Microsoft.MicrosoftEdge_8wekyb3d8bbwe\AC\MicrosoftEdge\User\Default\RACShare\Microsoft\Crypto\TokenBindingKeys\Keys

That contains a bunch of 100+ character file names in addition to the long path which pushes it over the 260 character limit.

Here is the full error:

Unhandled Exception: System.IO.PathTooLongException: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
   at System.IO.PathHelper.GetFullPathName()
   at System.IO.Path.LegacyNormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.GetFullPathInternal(String path)
   at ICSharpCode.SharpZipLib.Core.PathFilter.IsMatch(String name)
   at ICSharpCode.SharpZipLib.Core.FileSystemScanner.ScanDir(String directory, Boolean recurse)
   at ICSharpCode.SharpZipLib.Core.FileSystemScanner.ScanDir(String directory, Boolean recurse)
   at ICSharpCode.SharpZipLib.Core.FileSystemScanner.ScanDir(String directory, Boolean recurse)
   at ICSharpCode.SharpZipLib.Core.FileSystemScanner.ScanDir(String directory, Boolean recurse)
   at ICSharpCode.SharpZipLib.Core.FileSystemScanner.ScanDir(String directory, Boolean recurse)
   at ICSharpCode.SharpZipLib.Core.FileSystemScanner.ScanDir(String directory, Boolean recurse)
   at ICSharpCode.SharpZipLib.Core.FileSystemScanner.ScanDir(String directory, Boolean recurse)
   at ICSharpCode.SharpZipLib.Core.FileSystemScanner.ScanDir(String directory, Boolean recurse)
   at ICSharpCode.SharpZipLib.Core.FileSystemScanner.ScanDir(String directory, Boolean recurse)
   at ICSharpCode.SharpZipLib.Core.FileSystemScanner.ScanDir(String directory, Boolean recurse)
   at ICSharpCode.SharpZipLib.Core.FileSystemScanner.ScanDir(String directory, Boolean recurse)
   at ICSharpCode.SharpZipLib.Core.FileSystemScanner.ScanDir(String directory, Boolean recurse)
   at ICSharpCode.SharpZipLib.Core.FileSystemScanner.ScanDir(String directory, Boolean recurse)
   at ICSharpCode.SharpZipLib.Core.FileSystemScanner.ScanDir(String directory, Boolean recurse)
   at ICSharpCode.SharpZipLib.Core.FileSystemScanner.ScanDir(String directory, Boolean recurse)
   at ICSharpCode.SharpZipLib.Core.FileSystemScanner.ScanDir(String directory, Boolean recurse)
   at ICSharpCode.SharpZipLib.Core.FileSystemScanner.ScanDir(String directory, Boolean recurse)
   at ICSharpCode.SharpZipLib.Zip.FastZip.CreateZip(Stream outputStream, String sourceDirectory, Boolean recurse, String fileFilter, String directoryFilter)
   at kape.Program.CreateZip()
   at kape.Program.Main(String[] args)

**Comment by EricZimmerman** [comment]
yea this is a known issue with the containers. what did your --tdest look like? you can try something like --tdest c:\a to see if that helps. i will be of course updating things to gracefully handle this situation in the future by detecting the situation, saving the long file name to a text file, then saving a shortened version of the filename to a special directory. 

you can also NOT use any container options and you wont have this error as its specific to containers

**Comment by Gizmo44z** [comment]
I only had "C:\IR\Out" as the destination.  Since it's already a WIP, I'll mark as closed.

Thanks!
