### ISSUE TITLE
KAPE not copying all files from Target Source to Target Destination

### ISSUE THREAD

**Issue by jfarley248** [EricZimmerman/KapeFiles#58]
When using the Target iTunesBackups, KAPE does not copy many files from the Target Source to the Target Destination. At first I though this was an issue with KAPE copying files that were resident and had a .slack version of the file, or the file being empty but still existing. However I found that it failed to copy files that did have data, and no .slack file associated with it. 

I checked the Target file to see if anything was wrong, but it seems like it is correct:
```
Description: iTunes Backups
Author: Tony Knutson
Version: 1
Id: 7b4a98d9-b36a-40be-bacc-ad0102b0a8c3
RecreateDirectories: true
Targets:
    -
        Name: iTunes Backup Folder
        Category: Communications
        Path: C:\Users\*\AppData\Roaming\Apple\Mobilesync\Backup
        IsDirectory: True
        Recursive: True
        Comment: ""
    -
        Name: iTunes Backup Folder
        Category: Communications
        Path: C:\Users\*\AppData\Roaming\Apple Computer\Mobilesync\Backup
        IsDirectory: True
        Recursive: True
        Comment: ""
```

The missing files exist when I add the E01 to FTK and browse through FTK, as well as mounting the image and browsing the file system manually, the files are there. This is a sample of the output shown by my tool iTunes_Backup_Analyzer, along with lines I added to find correlation between missing files (FTK Imager, Mounted, KAPE, Notes). 

```
04-11 12:58 root         ERROR    Could not complete copy:
Source File: C:\Users\jfarl\Desktop\TRIAGE_RAW\I\Users\L_Organa\AppData\Roaming\Apple Computer\Mobilesync\Backup\75bb723de754790de5a870b3ef3c943602bff062\e7\e79835db903d8fd76a82abf9dda1294ec027e317
Destination File: C:\Users\jfarl\Desktop\TRIAGE_PARSED\ExternalDevices\iTunesBackups\iPhone 6s_FK1QCXU2GRYF\Recreated_File_Structure\CameraRollDomain\Media\PhotoData\momentanalysis
Exception was: [Errno 2] No such file or directory: '\\\\?\\C:\\Users\\jfarl\\Desktop\\TRIAGE_RAW\\I\\Users\\L_Organa\\AppData\\Roaming\\Apple Computer\\Mobilesync\\Backup\\75bb723de754790de5a870b3ef3c943602bff062\\e7\\e79835db903d8fd76a82abf9dda1294ec027e317'
Traceback (most recent call last):
  File "manifestParser.py", line 90, in recreateFile
  File "pathlib_revised\pathlib.py", line 21, in copyfile
  File "shutil.py", line 120, in copyfile
FileNotFoundError: [Errno 2] No such file or directory: '\\\\?\\C:\\Users\\jfarl\\Desktop\\TRIAGE_RAW\\I\\Users\\L_Organa\\AppData\\Roaming\\Apple Computer\\Mobilesync\\Backup\\75bb723de754790de5a870b3ef3c943602bff062\\e7\\e79835db903d8fd76a82abf9dda1294ec027e317'
FTK Imager: Exists
Mounted: Exists
KAPE Output: Doesn't Exist
Notes: File is empty, 0 bytes


04-11 12:58 root         ERROR    Could not complete copy:
Source File: C:\Users\jfarl\Desktop\TRIAGE_RAW\I\Users\L_Organa\AppData\Roaming\Apple Computer\Mobilesync\Backup\75bb723de754790de5a870b3ef3c943602bff062\e1\e19efc06fddeecdd2b56c28eb2484bfbe59572d5
Destination File: C:\Users\jfarl\Desktop\TRIAGE_PARSED\ExternalDevices\iTunesBackups\iPhone 6s_FK1QCXU2GRYF\Recreated_File_Structure\InstallDomain\Library\MobileInstallation\BackedUpState\SystemAppInstallState.plist
Exception was: [Errno 2] No such file or directory: '\\\\?\\C:\\Users\\jfarl\\Desktop\\TRIAGE_RAW\\I\\Users\\L_Organa\\AppData\\Roaming\\Apple Computer\\Mobilesync\\Backup\\75bb723de754790de5a870b3ef3c943602bff062\\e1\\e19efc06fddeecdd2b56c28eb2484bfbe59572d5'
Traceback (most recent call last):
  File "manifestParser.py", line 90, in recreateFile
  File "pathlib_revised\pathlib.py", line 21, in copyfile
  File "shutil.py", line 120, in copyfile
FileNotFoundError: [Errno 2] No such file or directory: '\\\\?\\C:\\Users\\jfarl\\Desktop\\TRIAGE_RAW\\I\\Users\\L_Organa\\AppData\\Roaming\\Apple Computer\\Mobilesync\\Backup\\75bb723de754790de5a870b3ef3c943602bff062\\e1\\e19efc06fddeecdd2b56c28eb2484bfbe59572d5'
FTK Imager: Exists
Mounted: Exists
KAPE Output: Doesn't exist
Notes: In FTK imager, file has a normal file and slack file associated with it


04-11 12:58 root         ERROR    Could not complete copy:
Source File: C:\Users\jfarl\Desktop\TRIAGE_RAW\I\Users\L_Organa\AppData\Roaming\Apple Computer\Mobilesync\Backup\75bb723de754790de5a870b3ef3c943602bff062\cb\cbea31c2494e7f8d37a299c733a4ceebb0957595
Destination File: C:\Users\jfarl\Desktop\TRIAGE_PARSED\ExternalDevices\iTunesBackups\iPhone 6s_FK1QCXU2GRYF\Recreated_File_Structure\CameraRollDomain\Media\PhotoData\protection
Exception was: [Errno 2] No such file or directory: '\\\\?\\C:\\Users\\jfarl\\Desktop\\TRIAGE_RAW\\I\\Users\\L_Organa\\AppData\\Roaming\\Apple Computer\\Mobilesync\\Backup\\75bb723de754790de5a870b3ef3c943602bff062\\cb\\cbea31c2494e7f8d37a299c733a4ceebb0957595'
Traceback (most recent call last):
  File "manifestParser.py", line 90, in recreateFile
  File "pathlib_revised\pathlib.py", line 21, in copyfile
  File "shutil.py", line 120, in copyfile
FileNotFoundError: [Errno 2] No such file or directory: '\\\\?\\C:\\Users\\jfarl\\Desktop\\TRIAGE_RAW\\I\\Users\\L_Organa\\AppData\\Roaming\\Apple Computer\\Mobilesync\\Backup\\75bb723de754790de5a870b3ef3c943602bff062\\cb\\cbea31c2494e7f8d37a299c733a4ceebb0957595'
FTK Imager: Exists
Mounted: Exists
KAPE Output: Doesn't exist
Notes: File is empty, 0 bytes

04-11 12:58 root         ERROR    Could not complete copy:
Source File: C:\Users\jfarl\Desktop\TRIAGE_RAW\I\Users\L_Organa\AppData\Roaming\Apple Computer\Mobilesync\Backup\75bb723de754790de5a870b3ef3c943602bff062\b0\b0648b7ba54bb2f1cafcd24fd8ba914518297125
Destination File: C:\Users\jfarl\Desktop\TRIAGE_PARSED\ExternalDevices\iTunesBackups\iPhone 6s_FK1QCXU2GRYF\Recreated_File_Structure\AppDomain-com.tinyspeck.chatlyio\Library\Beacon-d87474de2056448eac881647d2c2fc43-events.plist
Exception was: [Errno 2] No such file or directory: '\\\\?\\C:\\Users\\jfarl\\Desktop\\TRIAGE_RAW\\I\\Users\\L_Organa\\AppData\\Roaming\\Apple Computer\\Mobilesync\\Backup\\75bb723de754790de5a870b3ef3c943602bff062\\b0\\b0648b7ba54bb2f1cafcd24fd8ba914518297125'
Traceback (most recent call last):
  File "manifestParser.py", line 90, in recreateFile
  File "pathlib_revised\pathlib.py", line 21, in copyfile
  File "shutil.py", line 120, in copyfile
FileNotFoundError: [Errno 2] No such file or directory: '\\\\?\\C:\\Users\\jfarl\\Desktop\\TRIAGE_RAW\\I\\Users\\L_Organa\\AppData\\Roaming\\Apple Computer\\Mobilesync\\Backup\\75bb723de754790de5a870b3ef3c943602bff062\\b0\\b0648b7ba54bb2f1cafcd24fd8ba914518297125'
FTK Imager: Exists
Mounted: Exists
KAPE Output: Doesn't Exist
Notes: File has data
```

**Comment by EricZimmerman** [comment]
The issue is ftk imager. Mount the image with arsenal image mounter and try again. Please let me know.

**Comment by jfarley248** [comment]
Issue still persists. Tried mounting it read only and write temporary with Arsenal Image Mounter v2.4.26

**Comment by EricZimmerman** [comment]
Send me console log with debug switch enabled please.

Eric Zimmerman

Opinions stated, unless explicitly stated otherwise, are mine and not that
of my employer.

P // 501-313-3778

**Comment by EricZimmerman** [comment]
If you are using a single target please add the trace option too

Eric Zimmerman

Opinions stated, unless explicitly stated otherwise, are mine and not that
of my employer.

P // 501-313-3778

**Comment by jfarley248** [comment]
Here's is the KAPE log and the module log
[KAPE_Issue_58_ConsoleDebugTrace.txt](https://github.com/EricZimmerman/KapeFiles/files/3071127/KAPE_Issue_58_ConsoleDebugTrace.txt)
[iTunes_Backup_Analyzer.log](https://github.com/EricZimmerman/KapeFiles/files/3071128/iTunes_Backup_Analyzer.log)

**Comment by EricZimmerman** [comment]
i dont see the issue



Copied 326 (Deduplicated: 33) out of 359 files in 1.8390 seconds. See '*_copylog.txt' in 'C:\Users\jfarl\Desktop\TRIAGE_RAW' for copy details


what files or folders do you think should have been copied, but were not copied?

notice 33 files were deduped. you need to account for these. if you do NOT want dedupe, add the switch that turns that off with --tdd false

**Comment by EricZimmerman** [comment]
search for the "missing" files and you will see they were skipped:

   11908  Hashing 'F:\Users\L_Organa\AppData\Roaming\Apple Computer\Mobilesync\Backup\75bb723de754790de5a870b3ef3c943602bff062\e1\e19efc06fddeecdd2b56c28eb2484bfbe59572d5'
   11909  Skipping 'F:\Users\L_Organa\AppData\Roaming\Apple Computer\Mobilesync\Backup\75bb723de754790de5a870b3ef3c943602bff062\e1\e19efc06fddeecdd2b56c28eb2484bfbe59572d5' with SHA-1 'B22A659F6A8FC03AC63501596D660037D5443670' as a file with same hash has already been copied

**Comment by jfarley248** [comment]
You're exactly right I was missing the flag to not dedupe. Thank you

**Comment by EricZimmerman** [comment]
=)
