### ISSUE TITLE
Unhandled Exception: The data present in the reparse point buffer is invalid

### ISSUE THREAD

**Issue by reynas** [EricZimmerman/KapeFiles#580]
**KAPE version**

The version of KAPE you are running: 1.1.0.1

**Describe the bug**

```
.\kape.exe --tsource C: --tdest .\kape-target%d%m --tflush --target !custom-targetcompound --zip kape_target_zipped --mdest .\kape-module%d%m --mflush --zm true --module !custom-modulecompound --zpw password --debug

2021-11-30 10:46:39.8283 | D | Processing target: Gigatribe Files Windows Vista/7/8/10
2021-11-30 10:46:39.8283 | D | Expanding directory: 'C:\Users\\%user%\AppData\Local\Shalsoft\'
2021-11-30 10:46:39.8283 | D | 	'C:\ProgramData\AppData\Local\Shalsoft' does not exist. Skipping
2021-11-30 10:46:39.8283 | D | 	'C:\Users\Default\AppData\Local\Shalsoft' does not exist. Skipping
2021-11-30 10:46:39.8283 | D | 	'C:\Users\Default\AppData\Local\Shalsoft' does not exist. Skipping
2021-11-30 10:46:39.8283 | D | 	'C:\Users\defaultuser0\AppData\Local\Shalsoft' does not exist. Skipping
2021-11-30 10:46:39.8283 | D | 	'C:\Users\username1\AppData\Local\Shalsoft' does not exist. Skipping
2021-11-30 10:46:39.8283 | D | 	'C:\Users\username2\AppData\Local\Shalsoft' does not exist. Skipping
2021-11-30 10:46:39.8283 | D | 	'C:\Users\username3\AppData\Local\Shalsoft' does not exist. Skipping
2021-11-30 10:46:39.8283 | D | 	'C:\Users\username4\AppData\Local\Shalsoft' does not exist. Skipping
2021-11-30 10:46:39.8283 | D | 	'C:\Users\Public\AppData\Local\Shalsoft' does not exist. Skipping
2021-11-30 10:46:39.8283 | D | Files found: 0
2021-11-30 10:46:39.8283 | D | Processing target: Gigatribe Files Windows XP
2021-11-30 10:46:39.8283 | D | Expanding directory: 'C:\Documents and Settings\\%user%\\*\Application Data\Gigatribe\'
2021-11-30 10:46:41.4890 | F | (4392) The data present in the reparse point buffer is invalid: [C:\Users\username1\OneDrive - private]:    at Alphaleonis.Win32.Filesystem.Device.GetLinkTargetInfo(SafeFileHandle safeHandle, String reparsePath) in C:\Users\jjangli\Documents\GitHub\AlphaFS\AlphaFS\Device\Device.cs:line 469
   at Alphaleonis.Win32.Filesystem.File.GetLinkTargetInfoCore(KernelTransaction transaction, String reparsePath, Boolean continueOnException, PathFormat pathFormat) in C:\Users\jjangli\Documents\GitHub\AlphaFS\AlphaFS\Filesystem\File Class\File.GetLinkTargetInfo.cs:line 111
   at kape.Classes.Helpers.ResolveReparsePoints(String dir)
   at kape.Classes.Helpers.ExpandDirectory(String dir)
   at kape.Classes.Helpers.ExpandDirectory(String dir)
   at kape.Program.ExpandTarget(Target target)
   at kape.Program.ProcessTarget(Target target, String startDirectory)
   at kape.Program.LoadTargetFile(TargetCollection targetFile)
   at kape.Program.LoadTargetFile(TargetCollection targetFile)
   at kape.Program.LoadTargetFile(TargetCollection targetFile)
   at kape.Program.Main(String[] args)
2021-11-30 10:46:41.4971 | W | Unhandled exception! Attempting to write current Console Log to 'C:\Windows\Temp\Kape\2021-11-30T10_44_40_5598451_ConsoleLog.txt'
```
**To Reproduce**

We are not sure yet on how to reproduce. It was tested on two separate machines, both with OneDrive installed.
A similar setup was attempted, (an active OneDrive), but the error was not reproduced.

**Expected behavior**

A fix or the handling of the exception itself so kape does not stop. It should log and continue.

**Screenshots**
/

**Additional context**
We used the default P2P compound file (referencing Gigatribe, also default and unchanged).

**Comment by EricZimmerman** [comment]
i am hesitant to do this kind of thing: eat the error and just report it, because people will miss the error and then wonder why nothing was collected.

i always try to err on the side of letting the user make the decision here (and then make the decision to not collect the target causing the problem, perhaps getting it via other means) vs kape working around the error.

could it be the path in the target is just incorrect? look at the Expanding directory call:

2021-11-30 10:46:39.8283 | D | Expanding directory: 'C:\Documents and Settings\\%user%\\*\Application Data\Gigatribe\'

perhaps all those double \ is the issue?

can you clean those up and try again?

the fact that it works on some machines but not others leads me to this being a data corruption issue (per the error message) vs something kape is doing wrong.

**Comment by reynas** [comment]
Hi

Thanks for your quick reply to my issue report.


I fully agree that the user should make the decision, but the problem is that the user that can make that decision, is not always the person executing the program. Therefor I suggest to give that user an option, so that the user can decide to continue when an exception occurs, or just crash. If you inexperienced people execute Kape to collect evidence, crashing is not as clean as properly logging (which already happens) and continuing. (personal opinion of course).
Would adding an option to handle these alerts be an option, so the operator can accept the risk? Just thinking out loud.
I definitely agree with the fact that it is possible an underlying issue is causing this error in Kape and not Kape itself, troubleshooting the issue is not easy to do now.


Note that the double \ is not present in the original .tkape file (which we used). (This was an issue with github markup on my side.). We reference the original file: https://github.com/EricZimmerman/KapeFiles/blob/d9642bb6d3cdbafa62596cc2034430929e4dd691/Targets/P2P/Gigatribe.tkape

**Comment by EricZimmerman** [comment]
This is a rare issue and when I'm not willing to change because when that does happen I want people to be very aware of it

**Comment by Timanator** [comment]
Same error here on a zipped file set that I used before. The error points to this specific user path just like the previous users, which does not exist. 
C:\Users\jjangli\Documents\GitHub\AlphaFS\AlphaFS\Filesystem\Directory Class\Directory.CurrentDirectory.cs

**Comment by EricZimmerman** [comment]
Yeah this is a known issue that rarely occurs but when it does it can be a bit of a pain 

Version 2 should have it resolved

**Comment by Timanator** [comment]
Thanks EZ. After trying it on 3 diff machines with the same results I figure I'd harass you a bit instead of DaRathBum on Discord, God know I've drove him crazy over the years with my errors ;)
