### ISSUE TITLE
 Access is denied: [c:\System Volume Information]

### ISSUE THREAD

**Issue by nikitah4x** [EricZimmerman/KapeFiles#733]
**KAPE version**

KAPE version 1.3.0.0

**Describe the bug**

When I'm running kape.exe I'm getting in the start the following error:

`System.UnauthorizedAccessException: (5) Access is denied: [c:\System Volume Information]
   at Alphaleonis.Win32.NativeError.ThrowException(UInt32 errorCode, String readPath, String writePath) in C:\Users\jjangli\Documents\GitHub\AlphaFS\AlphaFS\NativeError.cs:line 126
   at Alphaleonis.Win32.Filesystem.Directory.SetCurrentDirectory(String path, PathFormat pathFormat) in C:\Users\jjangli\Documents\GitHub\AlphaFS\AlphaFS\Filesystem\Directory Class\Directory.CurrentDirectory.cs:line 126
   at kape.Classes.Helpers.ExpandDirectory(String dir)
   at kape.Program.ExpandTarget(Target target)
   at kape.Program.ProcessTarget(Target target, String startDirectory, Double targetVersion)
   at kape.Program.LoadTargetFile(TargetCollection targetFile)
   at kape.Program.LoadTargetFile(TargetCollection targetFile)
   at kape.Program.Main(String[] args)

Unhandled Exception: System.UnauthorizedAccessException: (5) Access is denied: [c:\System Volume Information]
   at Alphaleonis.Win32.NativeError.ThrowException(UInt32 errorCode, String readPath, String writePath) in C:\Users\jjangli\Documents\GitHub\AlphaFS\AlphaFS\NativeError.cs:line 126
   at Alphaleonis.Win32.Filesystem.Directory.SetCurrentDirectory(String path, PathFormat pathFormat) in C:\Users\jjangli\Documents\GitHub\AlphaFS\AlphaFS\Filesystem\Directory Class\Directory.CurrentDirectory.cs:line 126
   at kape.Classes.Helpers.ExpandDirectory(String dir)
   at kape.Program.ExpandTarget(Target target)
   at kape.Program.ProcessTarget(Target target, String startDirectory, Double targetVersion)
   at kape.Program.LoadTargetFile(TargetCollection targetFile)
   at kape.Program.LoadTargetFile(TargetCollection targetFile)
   at kape.Program.Main(String[] args)`

**To Reproduce**

1. Run the following cmd line kape.exe --target !SANS_Triage --tsource c: --tdest "%FOLDER%" --tflush --vss

**Expected behavior**

Everything to run without getting any kind of errors 

![image](https://user-images.githubusercontent.com/58976181/209526722-bdfc0493-0afa-4f6f-98e7-1990fa89740e.png)

**Additional context**

**Comment by scott-andrew-reid** [comment]
Seeing the same error on my home workstation.

**Comment by NassemKa** [comment]
HI EricZimmerman/KapeFiles I am getting same error running this command
".\kape.exe --tsource C: --tdest "C:\Users\----\Desktop\New folder (2)"
-tflush --target !BasicCollection"

**Comment by AndrewRathbun** [comment]
Eric is aware, he'll take a look today. Stay tuned

**Comment by EricZimmerman** [comment]
> --tdest "C:\Users\----\Desktop\New folder (2)"

in general, i would avoid such deep target destinations

looking at this now

**Comment by EricZimmerman** [comment]
this is fixed and will be going out in 1.3.0.1 here later today

**Comment by EricZimmerman** [comment]
1.3.0.1 is out. please test and we can reopen if need be.

**Comment by AndrewRathbun** [comment]
Tested successful on my end using the KapeTriage Target. Thanks for the quick fix!

**Comment by NassemKa** [comment]
Issue solved thanks Eric for the fix, best regards
