### ISSUE TITLE
C:\*\ in a target path causes a crash

### ISSUE THREAD

**Issue by sstraw** [EricZimmerman/KapeFiles#787]
**KAPE version**

1.3.0.2

**Describe the bug**

Using `C:\*\` in a path causes KAPE to crash.

**To Reproduce**
Below is an example target file and the resulting run. Here is a debug log with trace: [debug.log](https://github.com/EricZimmerman/KapeFiles/files/11236394/debug.log)

```yaml
Description: Crash recreate
Author: sean straw
Version: 1.1
Id: db8bd700-7636-4edf-8125-8477e3c3ae72
RecreateDirectories: true
Targets:
    -
        Name: Suspect line
        Category: Other
        Path: C:\*\
```

```
KAPE version 1.3.0.2, Author: Eric Zimmerman, Contact: https://www.kroll.com/kape (kape@kroll.com)

KAPE directory: C:\_ktools\kape
Command line:   --tsource e --tdest c:\windows\temp\tout --tflush --target crashtest

System info: Machine name: XXXXXXXX, 64-bit: True, User: sean.straw OS: Windows10 (10.0.19044)

Using Target operations
  Flushing target destination directory c:\windows\temp\tout
  Creating target destination directory c:\windows\temp\tout
Found 1 targets. Expanding targets to file list...
Object reference not set to an instance of an object.:    at kape.Classes.Helpers.ResolveReparsePoints(String dir)
   at kape.Classes.Helpers.ExpandDirectory(String dir)
   at kape.Program.ExpandTarget(Target target)
   at kape.Program.ProcessTarget(Target target, String startDirectory, Double targetVersion)
   at kape.Program.LoadTargetFile(TargetCollection targetFile)
   at kape.Program.Main(String[] args)
System.NullReferenceException: Object reference not set to an instance of an object.
   at kape.Classes.Helpers.ResolveReparsePoints(String dir)
   at kape.Classes.Helpers.ExpandDirectory(String dir)
   at kape.Program.ExpandTarget(Target target)
   at kape.Program.ProcessTarget(Target target, String startDirectory, Double targetVersion)
   at kape.Program.LoadTargetFile(TargetCollection targetFile)
   at kape.Program.Main(String[] args)

Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at kape.Classes.Helpers.ResolveReparsePoints(String dir)
   at kape.Classes.Helpers.ExpandDirectory(String dir)
   at kape.Program.ExpandTarget(Target target)
   at kape.Program.ProcessTarget(Target target, String startDirectory, Double targetVersion)
   at kape.Program.LoadTargetFile(TargetCollection targetFile)
   at kape.Program.Main(String[] args)
```

**Expected behavior**

Not crashing.

**Screenshots**

N/A

**Additional context**

This was in the RoamingProfile KAPE target linked below, but has since been removed as the target file was fixed.
 https://github.com/AndrewRathbun/KapeFiles/blob/7ddc5b523a34e074362f014d8bf7e4b6b2992a65/Targets/Windows/RoamingProfile.tkape

**Comment by EricZimmerman** [comment]
Does c:\ or the star in other places 2ork as expected?

I'll fix the crash but it seems not ideal to do that pattern at all since c:\ is equivalent

**Comment by sstraw** [comment]
I haven't seen issues with it elsewhere, but the crash appears for anything where it's `C:\*\some\path`, so I would assume its something to do with a filesystem file being included in the star

**Comment by EricZimmerman** [comment]
I know it works further down the path so I'll have to see what's special about it being at the very beginning

**Comment by Beercow** [comment]
Worked with @AndrewRathbun on this earlier this week. Hence the target changes. :-)
