### ISSUE TITLE
BIOS Parameter Block is invalid for an NTFS file system

### ISSUE THREAD

**Issue by krapgras** [EricZimmerman/KapeFiles#795]
**KAPE version**

v1.3.0.2

**Describe the bug**

When doing a collection on a disk image created from a USB drive formatted in NTFS format, I get "BIOS Parameter Block is invalid for an NTFS file system"

The usb was collected using FTK imager. 

**To Reproduce**

I used following command:

--tsource F:  --tdest X:\Output_Files\Test_Bitlocker\Kape --target !BasicCollection,!SANS_Triage --vss --gui

I also tried without the --vss without any difference and on different systems.

I get the following stack trace:

Could not copy file F:\$MFT to X:\Output_Files\Test_Bitlocker\Kape\F\$MFT. Error: BIOS Parameter Block is invalid for an NTFS file system
DiscUtils.InvalidFileSystemException: BIOS Parameter Block is invalid for an NTFS file system
   at DiscUtils.Ntfs.NtfsFileSystem..ctor(Stream stream)
   at RawCopy.Helper.VerifyFileSystemOpen(String path)
   at RawCopy.Helper.RawFileExists(String path)
   at kape.Classes.Copy.RawDiskLibCopy.Copy(String vssMountDirectory, Boolean deduplicate, Boolean usingContainer, TimeSpan findTime, Boolean simulateCopy)

Is there a fix for this?

I can share the image file as well but it is +- 5GB so can't add it to github.

**Comment by EricZimmerman** [comment]
What's the file system? Is this an e01?

**Comment by krapgras** [comment]
Yes it's a E01 from a windows boot drive. I just noticed it mounts it as FAT32 with arsenal image mounter. That might be the issue.

**Comment by krapgras** [comment]
I am mounting it with Arsenal in read only mode. But I tried different modes with same result.

**Comment by EricZimmerman** [comment]
Reformat as ntfs and do the test again.

**Comment by AndrewRathbun** [comment]
> I am mounting it with Arsenal in read only mode. But I tried different modes with same result.

Try Write Temporary with differencing file. That's how I always use AIM. I've had errors before in Read Only mode but those errors didn't persist in Write Temporary.

**Comment by krapgras** [comment]
> Reformat as ntfs and do the test again.

Did 2 tests:

1. Use media creation tool to create new bootable usb (Win10) => Autoreformats to FAT32 and creates same error.
2. Convert file system to NTFS manually => Works fine.

So indeed it seems to be linked to being FAT32 but still containing $MFT, etc.. files on the device.

I assume this is an edge case and therefor the expected behavior?

**Comment by EricZimmerman** [comment]
yep. its an odd case. i dont know why youd want to collect that target on a windows installation disk

**Comment by krapgras** [comment]
> yep. its an odd case. i dont know why youd want to collect that target on a windows installation disk

As mentioned I'm creating some automation and it was the closest USB drive i could find 😅
I guess if it's an edge case i'll leave it up to you guys if you want to keep track of it or just close it!

Thanks for the help anyways :)

**Comment by acfedp** [comment]
Hey Eric, 

Thank you very much for your wonderful script that helps me everyday at work. 

I am writing a new comment here because I have run into the same problem by copying the whole content of a USB Stick using your script. No mounting, it is a real USB Thumbdrive 8GB formatted in FAT32. 

the goal of my use of your script  is to copy automatically the logical content of the USB Thumbdrive in an image vhdx and a zip. 

I have created my own Target file: 

Description: Just get everything from a path
Author: acfedp
Version: 1.0
Id: b3ba844a-f7f8-441e-bb01-bcfa381bb3b1
RecreateDirectories: true
Targets:
    -
        Name: Traversal-All
        Category: copyall
        Path: C:\
        # Values starting with * need to be enclosed in single quotes because * denotes a reference in yaml
        # You can also do regex:<regex pattern> if more control is needed. i.e. FileMask: regex:(2019|DSC|Log).+\.(jpg|txt)
        FileMask: '*'
        Recursive: true
        Comment: Copy everything!

and the command line I execute is: 

kape.exe --tsource F: --tdest E:\667\_forensic_image\ --tflush --target DirectoryTraversalAll --tdd false --vhdx DT-00667 --zv false


Here is the error I get: 

Could not copy file F:\E2304240096.zip to E:\667\_forensic_image\F\E2304240096.zip. Error: BIOS Parameter Block is invalid for an NTFS file system
DiscUtils.InvalidFileSystemException: BIOS Parameter Block is invalid for an NTFS file system
   at DiscUtils.Ntfs.NtfsFileSystem..ctor(Stream stream)
   at RawCopy.Helper.VerifyFileSystemOpen(String path)
   at RawCopy.Helper.RawFileExists(String path)
   at kape.Classes.Copy.RawDiskLibCopy.Copy(String vssMountDirectory, Boolean deduplicate, Boolean usingContainer, TimeSpan findTime, Boolean simulateCopy)

WARNING: THERE WERE {.Count:N0} FILE COPY FAILURES! See the console log for details!!!


What's your opinion?

**Comment by EricZimmerman** [comment]
Format the thumb drive as ntfs. it's much faster and all around a better file system.

**Comment by acfedp** [comment]
I would if I could, but these stick are evidences that I am not allowed to modify.

**Comment by EricZimmerman** [comment]
youd be better off with robocopy then to be honest.

what put the evidence there? is this a subject drive? i can see that, but if not, change the process up stream to use ntfs if its part of some triage platform?

**Comment by acfedp** [comment]
I will implement my script using robocopy then, like you suggested. 

For the story, I am scripting a quick way to 
1) control sticks for antivirus boobytrap and so on that a service in our law enforcement is receiving every day
2) create a forensic copy of the stick for further process if the stick Is clean. 

 I don't want to create a physical image as it would be like shooting a flee with a bazooka, and it's where I planned your Wonderful soft to come in play.

**Comment by EricZimmerman** [comment]
i can look at fat32 support in v2 for sure. its doable

**Comment by acfedp** [comment]
It would be really great if you could. 

I think, other than in my use case, FAT32 is still a very used format for evidence I am finding on the field.
