### ISSUE TITLE
Running on 2012 R2 - 

### ISSUE THREAD

**Issue by HomeGrownCoder** [EricZimmerman/KapeFiles#86]
Multiple modules failing to validate while files are present. Program works without issue on windows 10. 

Error when validating 'C:\Users\testing\Desktop\Kape\Modules\NBTStat_NetBIOS_S
ssions.mkape'
System.MissingMethodException: Method not found: '!!0[] System.Array.Empty()'.
   at kape.Classes.Module.KapeModuleValidator..ctor()
   at kape.Program.ValidateConfigs()

Error when validating 'C:\Users\testing\Desktop\Kape\Modules\NetStat.mkape'
System.MissingMethodException: Method not found: '!!0[] System.Array.Empty()'.
   at kape.Classes.Module.KapeModuleValidator..ctor()
   at kape.Program.ValidateConfigs()

Error when validating 'C:\Users\testing\Desktop\Kape\Modules\NetworkDetails.mk
pe'
System.MissingMethodException: Method not found: '!!0[] System.Array.Empty()'.
   at kape.Classes.Module.KapeModuleValidator..ctor()
   at kape.Program.ValidateConfigs()

Error when validating 'C:\Users\testing\Desktop\Kape\Modules\PECmd.mkape'
System.MissingMethodException: Method not found: '!!0[] System.Array.Empty()'.
   at kape.Classes.Module.KapeModuleValidator..ctor()
   at kape.Program.ValidateConfigs()

Error when validating 'C:\Users\testing\Desktop\Kape\Modules\Plaso.mkape'
System.MissingMethodException: Method not found: '!!0[] System.Array.Empty()'.
   at kape.Classes.Module.KapeModuleValidator..ctor()
   at kape.Program.ValidateConfigs()

Error when validating 'C:\Users\testing\Desktop\Kape\Modules\PowerShell.mkape'
System.MissingMethodException: Method not found: '!!0[] System.Array.Empty()'.
   at kape.Classes.Module.KapeModuleValidator..ctor()
   at kape.Program.ValidateConfigs()

Error when validating 'C:\Users\testing\Desktop\Kape\Modules\PowershellOperati
nalFullEventLogView.mkape'
System.MissingMethodException: Method not found: '!!0[] System.Array.Empty()'.
   at kape.Classes.Module.KapeModuleValidator..ctor()
   at kape.Program.ValidateConfigs()

Error when validating 'C:\Users\testing\Desktop\Kape\Modules\PrintServiceOpera
ionalFullEventLogView.mkape'
System.MissingMethodException: Method not found: '!!0[] System.Array.Empty()'.
   at kape.Classes.Module.KapeModuleValidator..ctor()
   at kape.Program.ValidateConfigs()

Error when validating 'C:\Users\testing\Desktop\Kape\Modules\psfile.mkape'
System.MissingMethodException: Method not found: '!!0[] System.Array.Empty()'.
   at kape.Classes.Module.KapeModuleValidator..ctor()
   at kape.Program.ValidateConfigs()

Error when validating 'C:\Users\testing\Desktop\Kape\Modules\psinfo.mkape'
System.MissingMethodException: Method not found: '!!0[] System.Array.Empty()'.
   at kape.Classes.Module.KapeModuleValidator..ctor()
   at kape.Program.ValidateConfigs()

Error when validating 'C:\Users\testing\Desktop\Kape\Modules\pslist.mkape'
System.MissingMethodException: Method not found: '!!0[] System.Array.Empty()'.
   at kape.Classes.Module.KapeModuleValidator..ctor()
   at kape.Program.ValidateConfigs()

Error when validating 'C:\Users\testing\Desktop\Kape\Modules\psloggedon.mkape'
System.MissingMethodException: Method not found: '!!0[] System.Array.Empty()'.
   at kape.Classes.Module.KapeModuleValidator..ctor()
   at kape.Program.ValidateConfigs()

Error when validating 'C:\Users\testing\Desktop\Kape\Modules\psservice.mkape'
System.MissingMethodException: Method not found: '!!0[] System.Array.Empty()'.
   at kape.Classes.Module.KapeModuleValidator..ctor()
   at kape.Program.ValidateConfigs()

Error when validating 'C:\Users\testing\Desktop\Kape\Modules\RBCmd.mkape'
System.MissingMethodException: Method not found: '!!0[] System.Array.Empty()'.
   at kape.Classes.Module.KapeModuleValidator..ctor()
   at kape.Program.ValidateConfigs()

Error when validating 'C:\Users\testing\Desktop\Kape\Modules\RDP-Usage-events.
kape'
System.MissingMethodException: Method not found: '!!0[] System.Array.Empty()'.
   at kape.Classes.Module.KapeModuleValidator..ctor()
   at kape.Program.ValidateConfigs()

Error when validating 'C:\Users\testing\Desktop\Kape\Modules\RDPCoreTS.mkape'
System.MissingMethodException: Method not found: '!!0[] System.Array.Empty()'.
   at kape.Classes.Module.KapeModuleValidator..ctor()
   at kape.Program.ValidateConfigs()

Error when validating 'C:\Users\testing\Desktop\Kape\Modules\RecentFileCachePa
ser.mkape'
System.MissingMethodException: Method not found: '!!0[] System.Array.Empty()'.
   at kape.Classes.Module.KapeModuleValidator..ctor()
   at kape.Program.ValidateConfigs()

Error when validating 'C:\Users\testing\Desktop\Kape\Modules\RECmd.mkape'
System.MissingMethodException: Method not found: '!!0[] System.Array.Empty()'.
   at kape.Classes.Module.KapeModuleValidator..ctor()
   at kape.Program.ValidateConfigs()

Error when validating 'C:\Users\testing\Desktop\Kape\Modules\Registry_System.m
ape'
System.MissingMethodException: Method not found: '!!0[] System.Array.Empty()'.
   at kape.Classes.Module.KapeModuleValidator..ctor()
   at kape.Program.ValidateConfigs()

Error when validating 'C:\Users\testing\Desktop\Kape\Modules\RegRipper-ALL.mka
e'
System.MissingMethodException: Method not found: '!!0[] System.Array.Empty()'.
   at kape.Classes.Module.KapeModuleValidator..ctor()
   at kape.Program.ValidateConfigs()

Error when validating 'C:\Users\testing\Desktop\Kape\Modules\RegRipper-ntuser.
kape'
System.MissingMethodException: Method not found: '!!0[] System.Array.Empty()'.
   at kape.Classes.Module.KapeModuleValidator..ctor()
   at kape.Program.ValidateConfigs()

Error when validating 'C:\Users\testing\Desktop\Kape\Modules\RegRipper-sam.mka
e'
System.MissingMethodException: Method not found: '!!0[] System.Array.Empty()'.
   at kape.Classes.Module.KapeModuleValidator..ctor()
   at kape.Program.ValidateConfigs()

Error when validating 'C:\Users\testing\Desktop\Kape\Modules\RegRipper-securit
.mkape'
System.MissingMethodException: Method not found: '!!0[] System.Array.Empty()'.
   at kape.Classes.Module.KapeModuleValidator..ctor()
   at kape.Program.ValidateConfigs()

Error when validating 'C:\Users\testing\Desktop\Kape\Modules\RegRipper-softwar
.mkape'
System.MissingMethodException: Method not found: '!!0[] System.Array.Empty()'.
   at kape.Classes.Module.KapeModuleValidator..ctor()
   at kape.Program.ValidateConfigs()

Error when validating 'C:\Users\testing\Desktop\Kape\Modules\RegRipper-system.
kape'
System.MissingMethodException: Method not found: '!!0[] System.Array.Empty()'.
   at kape.Classes.Module.KapeModuleValidator..ctor()
   at kape.Program.ValidateConfigs()

Error when validating 'C:\Users\testing\Desktop\Kape\Modules\RoutingTable.mkap
'
System.MissingMethodException: Method not found: '!!0[] System.Array.Empty()'.
   at kape.Classes.Module.KapeModuleValidator..ctor()
   at kape.Program.ValidateConfigs()

Error when validating 'C:\Users\testing\Desktop\Kape\Modules\SBECmd.mkape'
System.MissingMethodException: Method not found: '!!0[] System.Array.Empty()'.
   at kape.Classes.Module.KapeModuleValidator..ctor()
   at kape.Program.ValidateConfigs()

Error when validating 'C:\Users\testing\Desktop\Kape\Modules\ScheduledTasksFul
EventLogView.mkape'
System.MissingMethodException: Method not found: '!!0[] System.Array.Empty()'.
   at kape.Classes.Module.KapeModuleValidator..ctor()
   at kape.Program.ValidateConfigs()

Error when validating 'C:\Users\testing\Desktop\Kape\Modules\SecurityEvents.mk
pe'
System.MissingMethodException: Method not found: '!!0[] System.Array.Empty()'.
   at kape.Classes.Module.KapeModuleValidator..ctor()
   at kape.Program.ValidateConfigs()

Error when validating 'C:\Users\testing\Desktop\Kape\Modules\SecurityFullEvent
ogView.mkape'
System.MissingMethodException: Method not found: '!!0[] System.Array.Empty()'.
   at kape.Classes.Module.KapeModuleValidator..ctor()
   at kape.Program.ValidateConfigs()

Error when validating 'C:\Users\testing\Desktop\Kape\Modules\SEPM_Logs.mkape'
System.MissingMethodException: Method not found: '!!0[] System.Array.Empty()'.
   at kape.Classes.Module.KapeModuleValidator..ctor()
   at kape.Program.ValidateConfigs()

Error when validating 'C:\Users\testing\Desktop\Kape\Modules\SigCheck.mkape'
System.MissingMethodException: Method not found: '!!0[] System.Array.Empty()'.
   at kape.Classes.Module.KapeModuleValidator..ctor()
   at kape.Program.ValidateConfigs()

Error when validating 'C:\Users\testing\Desktop\Kape\Modules\SMB-Server-Anonym
us-Logon.mkape'
System.MissingMethodException: Method not found: '!!0[] System.Array.Empty()'.
   at kape.Classes.Module.KapeModuleValidator..ctor()
   at kape.Program.ValidateConfigs()

Error when validating 'C:\Users\testing\Desktop\Kape\Modules\SparkCore.mkape'
System.MissingMethodException: Method not found: '!!0[] System.Array.Empty()'.
   at kape.Classes.Module.KapeModuleValidator..ctor()
   at kape.Program.ValidateConfigs()

Error when validating 'C:\Users\testing\Desktop\Kape\Modules\srum-dump.mkape'
System.MissingMethodException: Method not found: '!!0[] System.Array.Empty()'.
   at kape.Classes.Module.KapeModuleValidator..ctor()
   at kape.Program.ValidateConfigs()

Error when validating 'C:\Users\testing\Desktop\Kape\Modules\Symantec_Control_
og.mkape'
System.MissingMethodException: Method not found: '!!0[] System.Array.Empty()'.
   at kape.Classes.Module.KapeModuleValidator..ctor()
   at kape.Program.ValidateConfigs()

Error when validating 'C:\Users\testing\Desktop\Kape\Modules\Symantec_Daily_AV
mkape'
System.MissingMethodException: Method not found: '!!0[] System.Array.Empty()'.
   at kape.Classes.Module.KapeModuleValidator..ctor()
   at kape.Program.ValidateConfigs()

Error when validating 'C:\Users\testing\Desktop\Kape\Modules\Symantec_Security
Log.mkape'
System.MissingMethodException: Method not found: '!!0[] System.Array.Empty()'.
   at kape.Classes.Module.KapeModuleValidator..ctor()
   at kape.Program.ValidateConfigs()

Error when validating 'C:\Users\testing\Desktop\Kape\Modules\Symantec_System_L
g.mkape'
System.MissingMethodException: Method not found: '!!0[] System.Array.Empty()'.
   at kape.Classes.Module.KapeModuleValidator..ctor()
   at kape.Program.ValidateConfigs()

Error when validating 'C:\Users\testing\Desktop\Kape\Modules\Symantec_Tamper_P
otection_Log.mkape'
System.MissingMethodException: Method not found: '!!0[] System.Array.Empty()'.
   at kape.Classes.Module.KapeModuleValidator..ctor()
   at kape.Program.ValidateConfigs()

Error when validating 'C:\Users\testing\Desktop\Kape\Modules\SystemEvents.mkap
'
System.MissingMethodException: Method not found: '!!0[] System.Array.Empty()'.
   at kape.Classes.Module.KapeModuleValidator..ctor()
   at kape.Program.ValidateConfigs()

Error when validating 'C:\Users\testing\Desktop\Kape\Modules\SystemFullEventLo
View.mkape'
System.MissingMethodException: Method not found: '!!0[] System.Array.Empty()'.
   at kape.Classes.Module.KapeModuleValidator..ctor()
   at kape.Program.ValidateConfigs()

Error when validating 'C:\Users\testing\Desktop\Kape\Modules\TaskScheduler.mka
e'
System.MissingMethodException: Method not found: '!!0[] System.Array.Empty()'.
   at kape.Classes.Module.KapeModuleValidator..ctor()
   at kape.Program.ValidateConfigs()

Error when validating 'C:\Users\testing\Desktop\Kape\Modules\tcpvcon.mkape'
System.MissingMethodException: Method not found: '!!0[] System.Array.Empty()'.
   at kape.Classes.Module.KapeModuleValidator..ctor()
   at kape.Program.ValidateConfigs()

Error when validating 'C:\Users\testing\Desktop\Kape\Modules\TeraCopy-history.
kape'
System.MissingMethodException: Method not found: '!!0[] System.Array.Empty()'.
   at kape.Classes.Module.KapeModuleValidator..ctor()
   at kape.Program.ValidateConfigs()

Error when validating 'C:\Users\testing\Desktop\Kape\Modules\TeraCopy-main.mka
e'
System.MissingMethodException: Method not found: '!!0[] System.Array.Empty()'.
   at kape.Classes.Module.KapeModuleValidator..ctor()
   at kape.Program.ValidateConfigs()

Error when validating 'C:\Users\testing\Desktop\Kape\Modules\TS-LSM.mkape'
System.MissingMethodException: Method not found: '!!0[] System.Array.Empty()'.
   at kape.Classes.Module.KapeModuleValidator..ctor()
   at kape.Program.ValidateConfigs()

Error when validating 'C:\Users\testing\Desktop\Kape\Modules\TS-RCM.mkape'
System.MissingMethodException: Method not found: '!!0[] System.Array.Empty()'.
   at kape.Classes.Module.KapeModuleValidator..ctor()
   at kape.Program.ValidateConfigs()

Error when validating 'C:\Users\testing\Desktop\Kape\Modules\usbdeviceforensic
.mkape'
System.MissingMethodException: Method not found: '!!0[] System.Array.Empty()'.
   at kape.Classes.Module.KapeModuleValidator..ctor()
   at kape.Program.ValidateConfigs()

Error when validating 'C:\Users\testing\Desktop\Kape\Modules\WindowsEventLogs.
kape'
System.MissingMethodException: Method not found: '!!0[] System.Array.Empty()'.
   at kape.Classes.Module.KapeModuleValidator..ctor()
   at kape.Program.ValidateConfigs()

Error when validating 'C:\Users\testing\Desktop\Kape\Modules\WinPmem.mkape'
System.MissingMethodException: Method not found: '!!0[] System.Array.Empty()'.
   at kape.Classes.Module.KapeModuleValidator..ctor()
   at kape.Program.ValidateConfigs()

Error when validating 'C:\Users\testing\Desktop\Kape\Modules\WxTCmd.mkape'
System.MissingMethodException: Method not found: '!!0[] System.Array.Empty()'.
   at kape.Classes.Module.KapeModuleValidator..ctor()
   at kape.Program.ValidateConfigs()

One or more targets or modules failed validation. Fix the issues and try again

Press any key to exit

**Comment by EricZimmerman** [comment]
You are missing .net 4.6. Install it and try again. Nothing else can be
done before that as you do not have the minimum requirements in place.

Eric

**Comment by HomeGrownCoder** [comment]
Will grab it now, I looked around quite a bit and could not find the requirements tabled out anywhere. Sorry for the ask

**Comment by EricZimmerman** [comment]
no problem. ill add to docs now

**Comment by EricZimmerman** [comment]
https://ericzimmerman.github.io/KapeDocs/#!Pages\2.-Getting-started.md#Requirements

has a link to the installer if you need it.
